/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * @author Riyaz
 */
import java.sql.*;
import javax.swing.JOptionPane;

public class Purchase extends javax.swing.JFrame {
    Connection con;
    Statement st;
    ResultSet rs;
    PreparedStatement pst;
    
    /**
     * Creates new form Purchase
     */
    public Purchase() {
        initComponents();
        dbConnect dbc=new dbConnect();
        con=dbc.Connect();
        System.out.println("DB Connected");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cnamelbl = new javax.swing.JLabel();
        cnametxt = new javax.swing.JTextField();
        cphonelbl = new javax.swing.JLabel();
        cphonetxt = new javax.swing.JTextField();
        caddlbl = new javax.swing.JLabel();
        caddtxt = new javax.swing.JTextField();
        namelbl = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        qntylbl = new javax.swing.JLabel();
        qntytxt = new javax.swing.JTextField();
        amountlbl = new javax.swing.JLabel();
        amounttxt = new javax.swing.JTextField();
        sumupbtn = new javax.swing.JButton();
        datelbl = new javax.swing.JLabel();
        datetxt = new javax.swing.JTextField();
        unitplbl = new javax.swing.JLabel();
        unitptxt = new javax.swing.JTextField();
        resetbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        jLabel6.setText("jLabel6");

        jLabel7.setText("jLabel7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 0, 153)), "PURCHASE", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 0, 204))); // NOI18N

        cnamelbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cnamelbl.setText("Customer's Name:");

        cnametxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cnametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnametxtActionPerformed(evt);
            }
        });

        cphonelbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cphonelbl.setText("Phone no:");

        cphonetxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        caddlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        caddlbl.setText("Customer's Address:");

        namelbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        namelbl.setText("Product Name:");

        nametxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        qntylbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        qntylbl.setText("Quantity:");

        qntytxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        amountlbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        amountlbl.setText("Total Amount:");

        amounttxt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        sumupbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        sumupbtn.setText("Sum up");
        sumupbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumupbtnActionPerformed(evt);
            }
        });

        datelbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        datelbl.setText("Date:");

        unitplbl.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        unitplbl.setText("Unit Price:");

        resetbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        resetbtn.setText("Reset");
        resetbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetbtnActionPerformed(evt);
            }
        });

        backbtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(caddlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(qntylbl, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cnamelbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(qntytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(caddtxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(cnametxt, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cphonelbl)
                            .addComponent(datelbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(datetxt, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(cphonetxt))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sumupbtn)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(unitplbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(unitptxt, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62)
                .addComponent(resetbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(backbtn)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(amountlbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(amounttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cnamelbl)
                            .addComponent(cnametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cphonelbl)
                            .addComponent(cphonetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(caddlbl)
                                    .addComponent(caddtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(namelbl)
                                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(qntytxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(datelbl)
                                .addComponent(datetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(qntylbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sumupbtn)
                    .addComponent(resetbtn)
                    .addComponent(backbtn))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(amountlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(amounttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(unitplbl)
                            .addComponent(unitptxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cnametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnametxtActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
                this.setVisible(false) ;
                ComputerPeripherial cpm = new ComputerPeripherial() ;
                cpm.setLocationRelativeTo(null);// GUI comes in center
                cpm.setTitle("COMPUTER PERIPHERIAL MANAGEMENT");
                cpm.setSize(400,400);
                cpm.setVisible(true);
    }//GEN-LAST:event_backbtnActionPerformed

    private void resetbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetbtnActionPerformed
        // TODO add your handling code here:
        cnametxt.setText("");
        cphonetxt.setText("");
        caddtxt.setText("");
        datetxt.setText("");
        nametxt.setText("");
        qntytxt.setText("");
        unitptxt.setText("");
        amounttxt.setText("");
        cnametxt.requestFocus();
    }//GEN-LAST:event_resetbtnActionPerformed

    private void sumupbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumupbtnActionPerformed
        // TODO add your handling code here:
        
        if(cnametxt.getText().equals("")||cphonetxt.getText().equals("")||caddtxt.getText().equals("")||datetxt.getText().equals("")||nametxt.getText().equals("")||qntytxt.getText().equals(""))
        {
             JOptionPane.showMessageDialog(this, "Please enter all credentials",
                "Validation Error", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            try
            {
                int quantity= Integer.parseInt(qntytxt.getText());
               // System.out.println(quantity);
               String str1= nametxt.getText();
               pst=con.prepareStatement("select Price from addproducts where Name=?");
               pst.setString(1, str1);
               rs=pst.executeQuery();
               if(rs.next()){
               String s =Integer.toString(rs.getInt(1));
               unitptxt.setText(s);
               int price= Integer.parseInt(s);
               System.out.println(price);
               int pqr=price*quantity;
               System.out.println(pqr);
               String s1= Integer.toString(pqr);
               amounttxt.setText(s1);
                
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Information not found");
                }
               
                st = con.createStatement();
                String sqlstr="select * from customerdetail";
                rs = st.executeQuery(sqlstr);
                rs.last();
                String insert_c_sql="insert into customerdetail(CustomerName,Contact,Address,Date,ProductName,Quantity,UnitPrice,TotalAmount)"+" values(?,?,?,?,?,?,?,?)";
                pst=con.prepareStatement(insert_c_sql);
                pst.setString(1,cnametxt.getText());
                pst.setFloat(2,Float.parseFloat(cphonetxt.getText()));
                pst.setString(3,caddtxt.getText());
                pst.setString(4,datetxt.getText());
                pst.setString(5,nametxt.getText());
                pst.setInt(6,Integer.parseInt(qntytxt.getText()));
                pst.setInt(7,Integer.parseInt(unitptxt.getText()));
                pst.setInt(8,Integer.parseInt(amounttxt.getText()));
                int inserted_rows=pst.executeUpdate();
   
            }
            catch(Exception e) {System.out.println("Exception Generated:"+e);}
        }
    }//GEN-LAST:event_sumupbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountlbl;
    private javax.swing.JTextField amounttxt;
    private javax.swing.JButton backbtn;
    private javax.swing.JLabel caddlbl;
    private javax.swing.JTextField caddtxt;
    private javax.swing.JLabel cnamelbl;
    private javax.swing.JTextField cnametxt;
    private javax.swing.JLabel cphonelbl;
    private javax.swing.JTextField cphonetxt;
    private javax.swing.JLabel datelbl;
    private javax.swing.JTextField datetxt;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel namelbl;
    private javax.swing.JTextField nametxt;
    private javax.swing.JLabel qntylbl;
    private javax.swing.JTextField qntytxt;
    private javax.swing.JButton resetbtn;
    private javax.swing.JButton sumupbtn;
    private javax.swing.JLabel unitplbl;
    private javax.swing.JTextField unitptxt;
    // End of variables declaration//GEN-END:variables
}
